- name: Install Alacritty
  homebrew_cask:
    name: alacritty
    state: latest

- name: Install VS Code
  homebrew_cask:
    name: visual-studio-code
    state: latest
  notify: Install vscode-plugins

- name: Update coreutils
  homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    - coreutils
    - fd
    - ripgrep
    - xsv
    - bash # Updates version
    - openssh
    - wget
    - ssh-copy-id
    - fish
    - exa

- name: Install Git
  homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    - git
    - git-delta
    - git-absorb
    - gh # GitHub cli

- name: Install linters
  homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    - pgformatter
    - tflint
    - ansible-lint
    - clang-format
    - shellcheck

- name: Install IDE apps
  homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    - neovim
    - tmux
    - tmuxinator
    - fzf

- name: Install services
  homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    - kubectl
    - postgresql
    - vault
    - terraform
    - fnm
    - go

- name: Install MacOS binaries
  homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    # Required to use keychain to store GPG key credentials.
    - pinentry-mac
  when: ansible_facts['os_family'] == "Darwin"
