---
- name: Install neovim
  homebrew:
    name: neovim
    state: latest

- name: Install tmux
  homebrew:
    name: tmux
    state: latest

- name: Install tmuxinator
  homebrew:
    name: tmuxinator
    state: latest
