---
- name: Install neovim
  homebrew:
    name: neovim
    state: latest

- name: Install tmux
  homebrew:
    name: tmux
    state: latest

- name: Install tmuxinator
  homebrew:
    name: tmuxinator
    state: latest

- name: Install VS Code
  homebrew_cask:
    name: visual-studio-code
    state: latest
  notify: Install vscode-plugins
