---
- include_tasks: "packages.yaml"
- include_tasks: "languages.yaml"

- name: Set MacOS system settings
  become: true
  shell: "{{ ansible_env.DOTFILES_REPO }}/scripts/macos.sh"
  tags:
    - never
    - install

