---
- include_tasks: "packages.yaml"
- include_tasks: "languages.yaml"

- name: Set MacOS system settings
  become: true
  shell: "{{ ansible_env.DOTFILES_REPO }}/scripts/macos.sh"
  tags:
    - never
    - install
- name: Copy VS Code options
  synchronize:
    delete: false
    src: "{{ ansible_env.DOTFILES_REPO }}/vscode/"
    # TODO(allancalix): Make this work on linux.
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/"
  when: ansible_facts['os_family'] == "Darwin"
  tags:
    - never
    - install
