---
- name: Create static directory for readonly source code
  become: true
  file:
    path: /usr/local/share/source/third_party
    state: directory

- name: Install vendor spaceship-prompt
  become: true
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt
    dest: /usr/local/share/source/third_party/denysdovhan/spaceship-prompt
    update: true

- name: Inject spaceship-prompt environment variable
  lineinfile:
    state: present
    path: "{{ ansible_env.HOME }}/.zsh.local"
    line: "export SPACESHIP_ROOT=/usr/local/share/source/third_party/denysdovhan/spaceship-prompt"

- name: Sync dotfiles
  synchronize:
    delete: false
    src: dotfiles/
    dest: "{{ ansible_env.HOME }}"
    perms: false
    recursive: true
    rsync_opts:
        - "--exclude=.zsh.local"

- name: Link spaceship-prompt in zsh themes
  file:
    src: /usr/local/share/source/third_party/denysdovhan/spaceship-prompt/spaceship.zsh
    dest: "{{ ansible_env.HOME }}/.zsh/themes/prompt_spaceship_setup"
    state: link

- name: Copy VS Code options
  synchronize:
    delete: false
    src: vscode/
    # TODO(allancalix): Make this work on linux.
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/"

