---
- name: Create static directory for readonly source code
  become: true
  file:
    path: /usr/local/share/source/third_party
    state: directory

- name: Install vendor spaceship-prompt
  become: true
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt
    dest: /usr/local/share/source/third_party/denysdovhan/spaceship-prompt
    update: true

- name: Inject spaceship-prompt environment variable
  lineinfile:
    state: present
    path: "{{ ansible_env.HOME }}/.zsh.local"
    line: "export SPACESHIP_ROOT=/usr/local/share/source/third_party/denysdovhan/spaceship-prompt"

- name: Sync dotfiles
  synchronize:
    delete: false
    src: "{{ ansible_env.DOTFILES_REPO }}/dotfiles/"
    dest: "{{ ansible_env.HOME }}"
    perms: false
    recursive: true
    rsync_opts:
        - "--exclude=.zsh.local"
  notify: Run post install script

- name: Link spaceship-prompt in zsh themes
  file:
    src: /usr/local/share/source/third_party/denysdovhan/spaceship-prompt/spaceship.zsh
    dest: "{{ ansible_env.HOME }}/.zsh/themes/prompt_spaceship_setup"
    state: link

- name: Create neovim autoload directory
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload"
    state: directory

- name: Install neovim package manager
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
    mode: "u=rw-,g=rw-,o=r--"

- name: Copy VS Code options
  synchronize:
    delete: false
    src: "{{ ansible_env.DOTFILES_REPO }}/vscode/"
    # TODO(allancalix): Make this work on linux.
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/"

