- name: Development Machine
  hosts: localhost
  vars_files:
    - vars/common.yaml
  roles:
    - common
    - homebrew
    - rust
    - gnupg
    - dotfiles
    - role: darwin
      when: ansible_facts['os_family'] == "Darwin"
